### PR TITLE
Support PHP 7.2 by adding phpseclib/mcrypt_compat

### PR DESCRIPTION
**Pull request by querwurzel**

### CODE REVIEW

**Comment by Tealk** [comment]
nice work Thanks!

**Comment by TimerWolf** [comment]
I just get errors when i try to use this version, i use PHP 7.2.19

**Comment by querwurzelt** [comment]
Any more input than "errors"?

**Comment by TimerWolf** [comment]
I got this

> Function mcrypt_get_iv_size() is deprecated
>
> Open: /home/www/pastebin/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php
>
>    	/**
>    	 * Get the IV size for the cipher.
>    	 *
>    	 * @return int
>    	 */
>    	protected function getIvSize()
>    	{
>    		return mcrypt_get_iv_size($this->cipher, $this->mode);
>    	}
>

**Comment by querwurzel** [comment]
Just turn off deprecation warnings (E_ALL ^ E_DEPRECATED)

**Comment by TimerWolf** [comment]
That is very strange, as i already tested it and then it come another problem but i could enter the site when this was done but i could not click anywhere...

Seems to work now anyways, thanks alot!

**Pull request closed without merging**
